#!/usr/bin/env bash
set -Eeuo pipefail

ACTION="${1:-install}"
CONF_DIR="/etc/onlyoffice/docspace"

info() { printf '[INFO] %s\n' "$*"; }
ok()   { printf '[ OK ] %s\n' "$*"; }
die()  { printf '[FAIL] %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root inside the DocSpace LXC."
command -v python3 >/dev/null 2>&1 || die "python3 is required."
command -v mysql >/dev/null 2>&1 || die "mysql client is required."
[[ -d "$CONF_DIR" ]] || die "DocSpace configuration directory not found: $CONF_DIR"

ENVIRONMENT="$(awk -F= '/^ENVIRONMENT=/{print $2; exit}' "$CONF_DIR/systemd.env" 2>/dev/null || true)"
ENVIRONMENT="${ENVIRONMENT:-community}"
CONF="$CONF_DIR/appsettings.${ENVIRONMENT}.json"
[[ -r "$CONF" ]] || die "Cannot read $CONF"

case "$ACTION" in
  install|remove|status) ;;
  *) die "Usage: $0 [install|remove|status]" ;;
esac

python3 - "$CONF" "$ACTION" <<'PY'
import json
import os
import subprocess
import sys

conf_path, action = sys.argv[1], sys.argv[2]

with open(conf_path, "r", encoding="utf-8") as fh:
    cfg = json.load(fh)

try:
    conn = cfg["ConnectionStrings"]["default"]["connectionString"]
except Exception as exc:
    raise SystemExit(f"[FAIL] Cannot read MySQL connection string from {conf_path}: {exc}")

parts = {}
for item in conn.split(";"):
    if "=" not in item:
        continue
    key, value = item.split("=", 1)
    parts[key.strip().lower()] = value

host = parts.get("server", "localhost")
port = parts.get("port", "3306")
database = parts.get("database", "onlyoffice")
app_user = parts.get("user id") or parts.get("uid") or parts.get("user")
app_password = parts.get("password", "")

TRIGGER_INSERT = "cs_docspace_auto_activate_bi"
TRIGGER_UPDATE = "cs_docspace_auto_activate_bu"

def run(cmd, *, env=None, sql=None, check=False):
    p = subprocess.run(
        cmd,
        input=sql,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and p.returncode:
        raise SystemExit(f"[FAIL] MySQL command failed:\n{p.stderr.strip()}")
    return p

# Prefer local root/socket authentication when available. If DocSpace uses a
# dedicated DB host or socket root is unavailable, fall back to app credentials.
candidates = []
if host in ("localhost", "127.0.0.1", "::1"):
    candidates.append((["mysql", "--protocol=socket", "-uroot", "-D", database], os.environ.copy(), "local root/socket"))

if app_user:
    env = os.environ.copy()
    env["MYSQL_PWD"] = app_password
    candidates.append((
        ["mysql", "--batch", "--raw", "-h", host, "-P", str(port), "-u", app_user, "-D", database],
        env,
        f"DocSpace DB user {app_user}",
    ))

mysql_cmd = mysql_env = mysql_label = None
for cmd, env, label in candidates:
    p = run(cmd + ["-e", "SELECT 1;"], env=env)
    if p.returncode == 0:
        mysql_cmd, mysql_env, mysql_label = cmd, env, label
        break

if not mysql_cmd:
    details = []
    for cmd, env, label in candidates:
        p = run(cmd + ["-e", "SELECT 1;"], env=env)
        details.append(f"{label}: {p.stderr.strip()}")
    raise SystemExit("[FAIL] Could not connect to the DocSpace MySQL database.\n" + "\n".join(details))

print(f"[INFO] Database: {database} via {mysql_label}")

def mysql(sql, check=True):
    return run(mysql_cmd, env=mysql_env, sql=sql, check=check)

def scalar(sql):
    p = run(mysql_cmd + ["--skip-column-names", "-e", sql], env=mysql_env, check=True)
    return p.stdout.strip()

def trigger_exists(name):
    return scalar(
        "SELECT COUNT(*) FROM information_schema.TRIGGERS "
        f"WHERE TRIGGER_SCHEMA=DATABASE() AND TRIGGER_NAME='{name}';"
    ) == "1"

if action == "status":
    for name in (TRIGGER_INSERT, TRIGGER_UPDATE):
        print(f"{name}: {'installed' if trigger_exists(name) else 'missing'}")
    pending = scalar(
        "SELECT COUNT(*) FROM core_user "
        "WHERE status=1 AND removed=0 AND email<>'' "
        "AND COALESCE(sid,'')='' AND COALESCE(sso_name_id,'')='' "
        "AND activation_status IN (0,2);"
    )
    print(f"active local users still awaiting email activation: {pending}")
    raise SystemExit(0)

if action == "remove":
    mysql(
        f"DROP TRIGGER IF EXISTS {TRIGGER_INSERT};\n"
        f"DROP TRIGGER IF EXISTS {TRIGGER_UPDATE};\n"
    )
    print("[ OK ] Automatic local-user activation removed.")
    print("[INFO] Existing activation states were not changed.")
    raise SystemExit(0)

# install
# EmployeeActivationStatus: 0=NotActivated, 1=Activated, 2=Pending, 4=AutoGenerated
# EmployeeStatus.Active: 1
#
# Only normal local users are affected:
# - active account
# - not removed
# - non-empty email
# - no LDAP SID
# - no SSO name id
#
# We intentionally do NOT touch status=Pending invitation accounts. They still
# need to finish the registration/password flow; once they become Active, the
# UPDATE trigger removes the email-verification requirement.
ddl = f"""
DROP TRIGGER IF EXISTS {TRIGGER_INSERT};
DROP TRIGGER IF EXISTS {TRIGGER_UPDATE};

DELIMITER //
CREATE TRIGGER {TRIGGER_INSERT}
BEFORE INSERT ON core_user
FOR EACH ROW
BEGIN
  IF NEW.status = 1
     AND COALESCE(NEW.removed, 0) = 0
     AND COALESCE(NEW.email, '') <> ''
     AND COALESCE(NEW.sid, '') = ''
     AND COALESCE(NEW.sso_name_id, '') = ''
     AND NEW.activation_status IN (0, 2)
  THEN
    SET NEW.activation_status = 1;
  END IF;
END//

CREATE TRIGGER {TRIGGER_UPDATE}
BEFORE UPDATE ON core_user
FOR EACH ROW
BEGIN
  IF NEW.status = 1
     AND COALESCE(NEW.removed, 0) = 0
     AND COALESCE(NEW.email, '') <> ''
     AND COALESCE(NEW.sid, '') = ''
     AND COALESCE(NEW.sso_name_id, '') = ''
     AND NEW.activation_status IN (0, 2)
  THEN
    SET NEW.activation_status = 1;
  END IF;
END//
DELIMITER ;
"""
mysql(ddl)

# Fix currently active local accounts that are already waiting for verification.
mysql(
    "UPDATE core_user "
    "SET activation_status=1, last_modified=UTC_TIMESTAMP() "
    "WHERE status=1 AND removed=0 AND email<>'' "
    "AND COALESCE(sid,'')='' AND COALESCE(sso_name_id,'')='' "
    "AND activation_status IN (0,2);"
)

if not trigger_exists(TRIGGER_INSERT) or not trigger_exists(TRIGGER_UPDATE):
    raise SystemExit("[FAIL] Trigger verification failed.")

remaining = scalar(
    "SELECT COUNT(*) FROM core_user "
    "WHERE status=1 AND removed=0 AND email<>'' "
    "AND COALESCE(sid,'')='' AND COALESCE(sso_name_id,'')='' "
    "AND activation_status IN (0,2);"
)

print("[ OK ] Automatic local-user activation installed.")
print("[INFO] New/updated active local users are automatically set to activation_status=1.")
print("[INFO] Pending invitation accounts, SSO/LDAP users, removed users and AutoGenerated users are untouched.")
print(f"[INFO] Active local users still awaiting activation: {remaining}")
print("[INFO] Existing browser sessions can cache the old status; log out and sign in again if needed.")
PY
